bin: be sure to use the right python
On the buildfarm, when call vcsn compile, we sometimes get:

  terminate called after throwing an instance of 'std::runtime_error'
    what():  num_tapes: no such implementation
    failed signature:
      wordset<char_letters>, z
    available versions:
    failed command:
      vcsn compile -shared 'plugins/algos/num_tapes/wordset<char_letters>, z.cc' --extra-ldflags=''
    compiler error messages:
    File "build/35d/vcsn-2.0a/_inst/bin/vcsn-compile", line 59
      print(me + ": child was terminated by signal", -retcode, file=sys.stderr)
                                                                   ^
  SyntaxError: invalid syntax

that's because actually we ran Python 2, which does not understand
print as a function.

* configure.ac: Define VCSN_PYTHON for C++ code.
* bin/vcsn.in: Be sure to use the right version of Python.