nullableset: check the validity of conversions
Conversion from letterset to letterset is checked:

    In [2]: c = vcsn.context('lat<lal(abc), lal(xyz)>, b')
    In [3]: c.expression('a')
    RuntimeError: 1.1: {xyz}: conv: invalid label: a
      while converting expression "a" to RatE[{abc} x {xyz} -> B]
    a
    ^
      while reading expression: "a"

But it was not checked for nullableset, so we build `a|a` although
`a` is not supported by the second labelset.

There are no tests because the following commit (rat: convert the
expression after parsing, if needed) exercises this case.

* vcsn/labelset/nullableset.hh (conv): Check conversion.