rat: fix expressions on 4 tapes and more
join on 4 identities did not work.  The compiler (Clang and G++) was
unable to find the recursive call in the decltype return type:

    vcsn/algos/tuple.hh:59:16: error: no matching function for call to 'join'
        auto ids = join(rss.identities()...);
                   ^~~~
    [...]
    vcsn/core/join.hh:71:3: note: candidate template ignored: substitution failure
       [with ValueSet1 = vcsn::rat::identities, ValueSet2 = vcsn::rat::identities,
             ValueSet3 = vcsn::rat::identities, VSs = <vcsn::rat::identities>]:
       call to function 'join' that is neither visible in the template definition
            nor found by argument-dependent lookup
      join(ValueSet1 vs1, ValueSet2 vs2, ValueSet3 vs3, VSs&&... vs)
      ^
    vcsn/core/join.hh:44:3: note: candidate function template not viable: requires single argument 'vs', but 4 arguments were provided
      join(const ValueSet& vs)
      ^
    vcsn/core/join.hh:53:3: note: candidate function template not viable: requires 2 arguments, but 4 were provided
      join(ValueSet1 vs1, ValueSet2 vs2)
      ^
    1 error generated.

* vcsn/core/join.hh (join): Don't declare the return type, leave it to
the compiler, so that join is visible to join.
* tests/python/tuples.py: Check that case.