style: rename projecting functions as `project`
Unfortunately in a first version of this commit, we hit a problem with
GCC (I don't know if it's a GCC bug, or invalid C++ on which GCC
crashes, but not clang).  GCC 5 and 6 both crash before emitting any
error message.  Fortunately, GCC 4.9 does not, and reports:

    vcsn-compile: run: LC_ALL=C ccache g++-4.9 --coverage -I /home/forge/teamcityAgent/work/a0185dad9234e013/build/49c -I /home/forge/teamcityAgent/work/a0185dad9234e013  -I/usr/local/include -g -O2 -std=c++14 -fPIC -c -o '/home/forge/teamcityAgent/work/a0185dad9234e013/build/49c/lib/plugins/contexts/context<lat<letterset<char_letters>, wordset<char_letters>>, b>.31572.o' '/home/forge/teamcityAgent/work/a0185dad9234e013/build/49c/lib/plugins/contexts/context<lat<letterset<char_letters>, wordset<char_letters>>, b>.cc'
    /home/forge/teamcityAgent/work/a0185dad9234e013/libexec/vcsn-compile: child returned 4
    In file included from /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/core/rat/copy.hh:8:0,
                     from /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/copy.hh:9,
                     from /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/filter.hh:5,
                     from /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/accessible.hh:5,
                     from /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/ctx/instantiate.hh:3,
                     from /home/forge/teamcityAgent/work/a0185dad9234e013/build/49c/lib/plugins/contexts/context<lat<letterset<char_letters>, wordset<char_letters>>, b>.cc:8:
    /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/project.hh:40:59: error: template instantiation depth exceeds maximum of 900 (use -ftemplate-depth= to increase the maximum) substituting 'template<long unsigned int Tape, class Context> vcsn::expressionset<decltype (project<Tape>(rs.context()))> vcsn::detail::project(vcsn::expressionset<Context>&) [with long unsigned int Tape = 0ul; Context = <missing>]'
           -> expressionset<decltype(project<Tape>(rs.context()))>
                                                               ^
    /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/project.hh:40:59:   recursively required by substitution of 'template<long unsigned int Tape, class Context> vcsn::expressionset<decltype (project<Tape>(rs.context()))> vcsn::detail::project(vcsn::expressionset<Context>&) [with long unsigned int Tape = 0ul; Context = <missing>]'
    /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/project.hh:40:59:   required by substitution of 'template<long unsigned int Tape, class Context> vcsn::expressionset<decltype (project<Tape>(rs.context()))> vcsn::detail::project(vcsn::expressionset<Context>&) [with long unsigned int Tape = 0ul; Context = <missing>]'
    /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/project.hh:42:41:   template instantiation depth exceeds maximum of 900 (use -ftemplate-depth= to increase the maximum) substituting 'template<long unsigned int Tape, class Context> vcsn::expressionset<decltype (project<Tape>(rs.context()))> vcsn::detail::project(vcsn::expressionset<Context>&) [with long unsigned int Tape = 0ul; Context = <missing>]'
    /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/project.hh:40:59:   recursively required by substitution of 'template<long unsigned int Tape, class Context> vcsn::expressionset<decltype (project<Tape>(rs.context()))> vcsn::detail::project(vcsn::expressionset<Context>&) [with long unsigned int Tape = 0ul; Context = <missing>]'
    /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/project.hh:40:59:   required by substitution of 'template<long unsigned int Tape, class Context> vcsn::expressionset<decltype (project<Tape>(rs.context()))> vcsn::detail::project(vcsn::expressionset<Context>&) [with long unsigned int Tape = 0ul; Context = <missing>]'
    /home/forge/teamcityAgent/work/a0185dad9234e013/vcsn/algos/project.hh:42:41:   template instantiation depth exceeds maximum of 900 (use -ftemplate-depth= to increase the maximum) substituting 'template<long unsigned int Tape, class Context> vcsn::expressionset<decltype (project<Tape>(rs.context()))> vcsn::detail::project(vcsn::expressionset<Context>&) [with long unsigned int Tape = 0ul; Context = <missing>]'
    [...]
    g++-4.9: internal compiler error: Segmentation fault (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.

So we applied this change to project.hh:

         /// Project an expressionset to one tape.
         template <size_t Tape, typename Context>
         auto project(const expressionset<Context>& rs)
    -      -> expressionset<decltype(project<Tape>(rs.context()))>
         {
    -      return {project<Tape>(rs.context()),
    -              rs.identities()};
    +      // Weirdly enough, GCC enters an endless loop of instantiation
    +      // if we use this type as explicit function return type.
    +      return make_expressionset(project<Tape>(rs.context()), rs.identities());
         }

* vcsn/algos/derivation.hh, vcsn/algos/focus.hh,
* vcsn/algos/project-automaton.hh, vcsn/algos/project.hh,
* vcsn/algos/to-expansion.hh, vcsn/core/rat/copy.hh,
* vcsn/core/rat/expansionset.hh, vcsn/core/rat/expressionset.hh,
* vcsn/core/rat/printer.hh, vcsn/ctx/project-context.hh,
* vcsn/weightset/polynomialset.hh
(make_project_context, make_project): Rename as...
(project): this.