misc: more quotes in error messages
See #193: use quotes in error messages.

We have one regression:

    RuntimeError: 1.4-6: unexpected character: ⟩
    ab ⟩a⟨ ab
       ^^^
      while reading expression: ab ⟩a⟨ ab

now ends with:

      while reading expression: "ab \xe2\x9f\xa9a\xe2\x9f\xa8 ab"

I'm ambivalent on what to do here.

* vcsn/algos/make-context.hh, vcsn/dyn/algos.hxx,
* lib/vcsn/dyn/context-parser.cc: Use str_quote.
Remove useless namespace qualifications.

Adjust test suite.