tupleset: remove some std::make_tuple calls
We still need to explicitly call the contructor to please libstdc++
(which is apparently right according to
http://en.cppreference.com/w/cpp/utility/tuple/tuple):

/vcsn/labelset/tupleset.hh:500:14: error: chosen constructor is explicit
                                          in copy-initialization
       return {(set<I>().transpose(std::get<I>(l)))...};
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* vcsn/labelset/tupleset.hh: here.
Note only is this shorter, it's also more accurate on the types, if some
of these types were not std::tuples.