copy: avoid the use of std::function
For some reason GCC 4.8 does not like the previous code.  It seems that
there are issues with the lambdas:

ERROR: tests/python/union
=========================

/tmp/ccLP0zFC.s: Assembler messages:
/tmp/ccLP0zFC.s:47: Error: symbol `std::_Function_handler<bool (unsigned int), vcsn::{lambda(unsigned int)#1}>::_M_invoke(std::_Any_data const&, unsigned int)' is already defined
/tmp/ccLP0zFC.s:1288: Error: symbol `std::_Function_base::_Base_manager<vcsn::{lambda(unsigned int)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<vcsn::{lambda(unsigned int)#1}> const&, std::_Manager_operation)' is already defined

I couldn't find any relevant information, but anyway using a
std::function, which can be costly, is easy to avoid.

* vcsn/algos/copy.hh: Instead of using a std::function, use template parameter
for predicates.
* vcsn/algos/concatenate.hh: Adjust.