tests: update cell/line magic missing support
Now IPython reports

    UsageError: Cell magic `%%automaton` not found.
    UsageError: Line magic function `%demo` not found.

* tests/bin/ipynbdoctest.py: here.