dyn: x3: introduce an x3 parser for algebraic types
Based on vcsn/experiments/spirit/2-x3-one-grammar.

We use a plain old object function (printer) because can't use the
"overloaded" trick with boost::apply_visitor, with GCC7 we have
failures:

    /usr/include/boost/variant/detail/apply_visitor_unary.hpp: In instantiation of ‘static decltype(auto) boost::detail::variant::result_multideduce1<Visitor, Variant>::deduce_impl(It, unsigned int) [with It = boost::mpl::l_iter<boost::mpl::list5<vcsn::dyn::ast::oneset, vcsn::dyn::ast::letterset, vcsn::dyn::ast::wordset, vcsn::dyn::ast::expressionset, std::vector<vcsn::dyn::ast::labelset> > >; Visitor = const vcsn::dyn::ast::overload<vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::oneset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::letterset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::wordset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::expressionset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const std::vector<vcsn::dyn::ast::labelset, std::allocator<vcsn::dyn::ast::labelset> >&)> >; Variant = const vcsn::dyn::ast::labelset]’:
    /usr/include/boost/variant/detail/apply_visitor_unary.hpp:127:27:   required from ‘static decltype(auto) boost::detail::variant::result_multideduce1<Visitor, Variant>::deduce() [with Visitor = const vcsn::dyn::ast::overload<vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::oneset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::letterset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::wordset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::expressionset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const std::vector<vcsn::dyn::ast::labelset, std::allocator<vcsn::dyn::ast::labelset> >&)> >; Variant = const vcsn::dyn::ast::labelset]’
    /usr/include/boost/variant/detail/apply_visitor_unary.hpp:134:67:   required from ‘struct boost::detail::variant::result_wrapper1<const vcsn::dyn::ast::overload<vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::oneset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::letterset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::wordset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::expressionset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const std::vector<vcsn::dyn::ast::labelset, std::allocator<vcsn::dyn::ast::labelset> >&)> >, const vcsn::dyn::ast::labelset>’
    /usr/include/boost/variant/detail/apply_visitor_unary.hpp:165:71:   required from ‘decltype(auto) boost::apply_visitor(const Visitor&, Visitable&, typename boost::disable_if<boost::detail::variant::has_result_type<Visitor> >::type*) [with Visitor = vcsn::dyn::ast::overload<vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::oneset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::letterset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::wordset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::expressionset&)>, vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const std::vector<vcsn::dyn::ast::labelset, std::allocator<vcsn::dyn::ast::labelset> >&)> >; Visitable = const vcsn::dyn::ast::labelset; typename boost::disable_if<boost::detail::variant::has_result_type<Visitor> >::type = void]’
    ../../lib/vcsn/dyn/ctx-ast.hh:116:12:   required from here
    /usr/include/boost/variant/detail/apply_visitor_unary.hpp:123:21: error: request for member ‘operator()’ is ambiguous
             return vis()( boost::declval< value_t& >() );
                    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from ../../lib/vcsn/dyn/ctx-parser.cc:14:0:
    ../../lib/vcsn/dyn/ctx-ast.hh:106:48: note: candidates are: vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const std::vector<vcsn::dyn::ast::labelset>&)>
               [&o](const std::vector<labelset>& arg)
                                                    ^
    ../../lib/vcsn/dyn/ctx-ast.hh:105:40: note:                 vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::expressionset&)>
               [&o](const expressionset& arg){ o << arg; },
                                            ^
    ../../lib/vcsn/dyn/ctx-ast.hh:104:34: note:                 vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::wordset&)>
               [&o](const wordset& arg)      { o << arg; },
                                      ^
    ../../lib/vcsn/dyn/ctx-ast.hh:103:36: note:                 vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::letterset&)>
               [&o](const letterset& arg)    { o << arg; },
                                        ^
    ../../lib/vcsn/dyn/ctx-ast.hh:102:33: note:                 vcsn::dyn::ast::operator<<(std::ostream&, const vcsn::dyn::ast::labelset&)::<lambda(const vcsn::dyn::ast::oneset&)>
              ([&o](const oneset& arg)       { o << arg; },
                                     ^

* lib/vcsn/dyn/config.hh: New.
* lib/vcsn/dyn/ctx-ast.hh: New.
* lib/vcsn/dyn/ctx-parser.cc: New.
* lib/vcsn/dyn/ctx-parser.hh: New.
* lib/vcsn/dyn/error-handler.hh: New.
* tests/unit/context.cc: New.
* tests/unit/context.chk: New.